@echo off
echo Copying .env-general-example to .env-general...
copy .env-general-example .env-general

echo Copying .env-blum-example to .env-blum...
copy .env-blum-example .env-blum

echo Copying .env-tomarket-example to .env-tomarket...
copy .env-tomarket-example .env-tomarket

echo Copying .env-rockyrabbit-example to .env-rockyrabbit...
copy .env-rockyrabbit-example .env-rockyrabbit

echo Copying .env-timefarm-example to .env-timefarm...
copy .env-timefarm-example .env-timefarm

echo Copying .env-dotcoin-example to .env-dotcoin...
copy .env-dotcoin-example .env-dotcoin

echo Copying .env-lostdogs-example to .env-lostdogs...
copy .env-lostdogs-example .env-lostdogs

echo Copying .env-major-example to .env-major...
copy .env-major-example .env-major

echo Copying .env-pocketfi-example to .env-pocketfi...
copy .env-pocketfi-example .env-pocketfi

echo Please edit the .env-general file to add your API_ID and API_HASH after Installation.
echo Installing dependencies...
npm install
pause